version: '2'

networks:
  prodnetwork:
    driver: bridge

services:
 jenkins:
  image: devopsevd/jenkins:2.60.1
  ports:
    - "18080:8080"
  networks:
    - prodnetwork
  depends_on:
    - sonar
  environment:
    - SONAR_PORT=9000
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock

 sonar:
  image: devopsevd/sonar:5.6.3
  ports:
   - "19000:9000"
  networks:
    - prodnetwork
